import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import "./styles.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Your App Title</title>
        {/* 其他头部内容 */}
      </head>
      <body style={{ fontFamily: 'ZCOOL KuaiLe , sans-serif' }}>
        {children}
      </body>
    </html>
  );
}
